### ISSUE TITLE
cold start 問題に対処する

### ISSUE THREAD

**Issue by 75asa** [k-gen/pigeon-message#3]
いつスラッシュコマンドを実行してもすぐにレスポンスがくるように

**Comment by 75asa** [comment]
Cloud Run x Cloud Function x Heroku x GAE x AWS Lambda とかにしたい

**Comment by k-gen** [comment]
@75asa 
GlitchからCloud Runに移行しました。
最小インスタンス数を0→3に設定しているのでコールドスタート改善されているはず...！

**Comment by 75asa** [comment]
[![LGTM](https://lgtm.page.link/7ToAJwfvEiJdFjnw8)](https://media2.giphy.com/media/3oz8xAFtqoOUUrsh7W/200w.gif)
